translate: Add Russian translation
Davidoc26/wallpaper-selector pull request #16
Opened 2024-01-21 17:07 UTC by fisuri

2024-01-22 13:11 UTC, fisuri commented
[patch](https://raw.githubusercontent.com/fisuri/wallpaper-selector/main/translate%3A%20Add%20Russian%20translation.patch)

2024-01-26 08:53 UTC, Davidoc26 requested changes
Corrections needed

2024-01-26 08:53 UTC, Davidoc26 commented on po/ru.po
> +# Italian translation for io.github.davidoc26.wallpaper_selector.
Need correction

2024-01-26 08:53 UTC, Davidoc26 commented on po/ru.po
> +"Language-Team: Italian <>\n"
Need correction here (and lines 13, 14, 15)

2024-01-28 18:19 UTC, Davidoc26 approved these changes

2024-01-28 18:25 UTC, merged